name: Simple CI

on:
  push:
    branches: [main, staging, development]
  pull_request:
    branches: [main, staging, development]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.local/bin" >> $GITHUB_PATH
      
      - name: Create virtual environment and install dependencies
        run: |
          uv venv
          source .venv/bin/activate
          uv sync
          echo "VIRTUAL_ENV=$PWD/.venv" >> $GITHUB_ENV
          echo "$PWD/.venv/bin" >> $GITHUB_PATH
      
      - name: Verify installation
        run: |
          which python
          which ruff || echo "ruff not found in PATH"
          uv pip list | head -20
      
      - name: Run ruff lint
        run: |
          source .venv/bin/activate
          python -m ruff check . || uv run ruff check .
      
      - name: Run mypy type check
        run: |
          source .venv/bin/activate
          python -m mypy src/ --strict || uv run mypy src/ --strict
        continue-on-error: true
      
      - name: Run unit tests
        run: |
          source .venv/bin/activate
          PACE_MIN_SECONDS=0 PYTHONPATH=src python -m pytest tests/unit/ -q --tb=short
        continue-on-error: true
      
      - name: Summary
        if: always()
        run: |
          echo "### CI Run Complete"
          echo "Python: $(python --version)"
          echo "Working Directory: $(pwd)"
          echo "Virtual Env: $VIRTUAL_ENV"